<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE Library [
        <!ELEMENT Library (publications, pupils)>

        <!ELEMENT publications (publication+)>
        <!ELEMENT publication (title)>
        <!ATTLIST publication type (Book | Article | Journal | Newspaper) #REQUIRED>
        <!ELEMENT title (#PCDATA)>

        <!ELEMENT pupils (pupil+)>
        <!ELEMENT pupil (birthdate, booksRead)>
        <!ATTLIST pupil name CDATA #REQUIRED
                        surname CDATA #REQUIRED>
        <!ELEMENT birthdate (#PCDATA)>
        <!ELEMENT booksRead (#PCDATA)>
        ]>

<Library>
    <publications>
        <publication type="Book">
            <title>The Hunger Games</title>
        </publication>
        <publication type="Book">
            <title>Harry Potter and the Sorcerer's Stone</title>
        </publication>
        <publication type="Article">
            <title>Teslaâ€™s Pay Deal to Keep Elon Musk: All or Nothing</title>
        </publication>
        <publication type="Article">
            <title>2018 Oscar Nominations: What to Expect</title>
        </publication>
        <publication type="Journal">
            <title>Rolling Stone #1302</title>
        </publication>
        <publication type="Newspaper">
            <title>The Guardian, Tuesday, 23 January 2018</title>
        </publication>
        <publication type="Newspaper">
            <title>The Wall Street Journal, January 22, 2018</title>
        </publication>
        <publication type="Article">
            <title>Is Schizophrenia Really a Brain Disease?</title>
        </publication>
        <publication type="Book">
            <title>Pride and Prejudice</title>
        </publication>
        <publication type="Journal">
            <title>TIME Magazine Vol. 190, No. 27</title>
        </publication>
        <publication type="Article">
            <title>Marijuana Withdrawal Syndrome</title>
        </publication>
        <publication type="Newspaper">
            <title>The New York Times, MONDAY, JANUARY 22, 2018</title>
        </publication>
        <publication type="Book">
            <title>The Chronicles of Narnia</title>
        </publication>
        <publication type="Journal">
            <title>Cosmopolitan, December 2017</title>
        </publication>
        <publication type="Journal">
            <title>Maxim, November/December 2017</title>
        </publication>
        <publication type="Newspaper">
            <title>China Daily, January 23, 2018</title>
        </publication>
        <publication type="Book">
            <title>The Lord of the Rings</title>
        </publication>
        <publication type="Book">
            <title>The Da Vinci Code</title>
        </publication>
        <publication type="Article">
            <title>Vaccines - A Two-Edged Sword</title>
        </publication>
        <publication type="Article">
            <title>God And Religion: Is It All In Our Heads?</title>
        </publication>
        <publication type="Book">
            <title>Alice's Adventures in Wonderland</title>
        </publication>
        <publication type="Book">
            <title>Romeo and Juliet</title>
        </publication>
    </publications>

    <pupils>
        <pupil name="Guillermo" surname="Francis">
            <birthdate>14.02.2004</birthdate>
            <booksRead>3</booksRead>
        </pupil>
        <pupil name="Roland" surname="Knight">
            <birthdate>25.10.2008</birthdate>
            <booksRead>2</booksRead>
        </pupil>
        <pupil name="Gerardo" surname="Richardson">
            <birthdate>04.11.2005</birthdate>
            <booksRead>7</booksRead>
        </pupil>
        <pupil name="Olga" surname="Brewer">
            <birthdate>04.04.2002</birthdate>
            <booksRead>1</booksRead>
        </pupil>
        <pupil name="Essie" surname="Manning">
            <birthdate>24.02.2006</birthdate>
            <booksRead>7</booksRead>
        </pupil>
        <pupil name="Juan" surname="Sandoval">
            <birthdate>30.05.2009</birthdate>
            <booksRead>15</booksRead>
        </pupil>
        <pupil name="Moses" surname="Gregory">
            <birthdate>19.10.2004</birthdate>
            <booksRead>1</booksRead>
        </pupil>
        <pupil name="Hugh" surname="Arnold">
            <birthdate>31.05.2010</birthdate>
            <booksRead>0</booksRead>
        </pupil>
        <pupil name="Lee" surname="Douglas">
            <birthdate>12.07.2010</birthdate>
            <booksRead>1</booksRead>
        </pupil>
        <pupil name="Shelly" surname="Sims">
            <birthdate>09.10.2005</birthdate>
            <booksRead>2</booksRead>
        </pupil>
        <pupil name="Ruben" surname="George">
            <birthdate>15.06.2002</birthdate>
            <booksRead>8</booksRead>
        </pupil>
        <pupil name="Johnnie" surname="Stevenson">
            <birthdate>02.09.2007</birthdate>
            <booksRead>4</booksRead>
        </pupil>
        <pupil name="Edith" surname="Crawford">
            <birthdate>19.10.2004</birthdate>
            <booksRead>6</booksRead>
        </pupil>
        <pupil name="Dana" surname="Wade">
            <birthdate>21.02.2009</birthdate>
            <booksRead>0</booksRead>
        </pupil>
        <pupil name="Colleen" surname="Flowers">
            <birthdate>15.12.2006</birthdate>
            <booksRead>8</booksRead>
        </pupil>
        <pupil name="Raul" surname="Fernandez">
            <birthdate>17.07.2002</birthdate>
            <booksRead>5</booksRead>
        </pupil>
        <pupil name="Isabel" surname="Hines">
            <birthdate>05.06.2011</birthdate>
            <booksRead>2</booksRead>
        </pupil>
        <pupil name="Joey" surname="Adkins">
            <birthdate>16.07.2001</birthdate>
            <booksRead>13</booksRead>
        </pupil>
        <pupil name="Daisy" surname="Daniels">
            <birthdate>10.08.2009</birthdate>
            <booksRead>5</booksRead>
        </pupil>
        <pupil name="Dianne" surname="Ortega">
            <birthdate>03.07.2005</birthdate>
            <booksRead>3</booksRead>
        </pupil>
    </pupils>
</Library>