<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE Pupils [
        <!ELEMENT Pupils (pupil+)>
        <!ELEMENT pupil (birthdate, booksRead)>
        <!ATTLIST pupil name CDATA #REQUIRED
                surname CDATA #REQUIRED>
        <!ELEMENT birthdate (#PCDATA)>
        <!ELEMENT booksRead (#PCDATA)>
        ]>

<Pupils>
    <pupil name="Guillermo" surname="Francis">
        <birthdate>14.02.2004</birthdate>
        <booksRead>3</booksRead>
    </pupil>
    <pupil name="Roland" surname="Knight">
        <birthdate>25.10.2008</birthdate>
        <booksRead>2</booksRead>
    </pupil>
    <pupil name="Gerardo" surname="Richardson">
        <birthdate>04.11.2005</birthdate>
        <booksRead>7</booksRead>
    </pupil>
    <pupil name="Olga" surname="Brewer">
        <birthdate>04.04.2002</birthdate>
        <booksRead>1</booksRead>
    </pupil>
    <pupil name="Essie" surname="Manning">
        <birthdate>24.02.2006</birthdate>
        <booksRead>7</booksRead>
    </pupil>
    <pupil name="Juan" surname="Sandoval">
        <birthdate>30.05.2009</birthdate>
        <booksRead>15</booksRead>
    </pupil>
    <pupil name="Moses" surname="Gregory">
        <birthdate>19.10.2004</birthdate>
        <booksRead>1</booksRead>
    </pupil>
    <pupil name="Hugh" surname="Arnold">
        <birthdate>31.05.2010</birthdate>
        <booksRead>0</booksRead>
    </pupil>
    <pupil name="Lee" surname="Douglas">
        <birthdate>12.07.2010</birthdate>
        <booksRead>1</booksRead>
    </pupil>
    <pupil name="Shelly" surname="Sims">
        <birthdate>09.10.2005</birthdate>
        <booksRead>2</booksRead>
    </pupil>
    <pupil name="Ruben" surname="George">
        <birthdate>15.06.2002</birthdate>
        <booksRead>8</booksRead>
    </pupil>
    <pupil name="Johnnie" surname="Stevenson">
        <birthdate>02.09.2007</birthdate>
        <booksRead>4</booksRead>
    </pupil>
    <pupil name="Edith" surname="Crawford">
        <birthdate>19.10.2004</birthdate>
        <booksRead>6</booksRead>
    </pupil>
    <pupil name="Dana" surname="Wade">
        <birthdate>21.02.2009</birthdate>
        <booksRead>0</booksRead>
    </pupil>
    <pupil name="Colleen" surname="Flowers">
        <birthdate>15.12.2006</birthdate>
        <booksRead>8</booksRead>
    </pupil>
    <pupil name="Raul" surname="Fernandez">
        <birthdate>17.07.2002</birthdate>
        <booksRead>5</booksRead>
    </pupil>
    <pupil name="Isabel" surname="Hines">
        <birthdate>05.06.2011</birthdate>
        <booksRead>2</booksRead>
    </pupil>
    <pupil name="Joey" surname="Adkins">
        <birthdate>16.07.2001</birthdate>
        <booksRead>13</booksRead>
    </pupil>
    <pupil name="Daisy" surname="Daniels">
        <birthdate>10.08.2009</birthdate>
        <booksRead>5</booksRead>
    </pupil>
    <pupil name="Dianne" surname="Ortega">
        <birthdate>03.07.2005</birthdate>
        <booksRead>3</booksRead>
    </pupil>
</Pupils>